# Generated by Django 3.0.4 on 2020-03-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazines',
            new_name='Magazine',
        ),
    ]
