# Generated by Django 3.0.4 on 2020-03-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20200325_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
