# Generated by Django 3.0.4 on 2020-03-26 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0005_auto_20200325_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_loans',
            field=models.ManyToManyField(through='library_app.BookLoan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
