# Generated by Django 3.0.4 on 2020-03-26 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0006_auto_20200326_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.Magazine')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_loans',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_loans', models.ManyToManyField(through='library_app.BookLoan', to='library_app.Book')),
                ('magazine_loans', models.ManyToManyField(through='library_app.MagazineLoan', to='library_app.Magazine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='magazineloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.Profile'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.Profile'),
        ),
    ]
