# Generated by Django 3.0.4 on 2020-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_auto_20200326_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='issue',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
