# Generated by Django 3.0.4 on 2020-03-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_magazine_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazineloan',
            old_name='book',
            new_name='magazine',
        ),
    ]
