# Generated by Django 3.0.4 on 2020-03-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_auto_20200326_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
