# Generated by Django 3.0.4 on 2020-03-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_bookloan_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineloan',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
