# Generated by Django 3.0.4 on 2020-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_magazineloan_overdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='magazineloan',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
